# Generated by Django 3.1.2 on 2020-11-16 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
